baseURL: https://yolandajin.com # todo: change site url.
title: Yolanda (Yinuo) Jin # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  logo: logo.jpeg # todo: add your custom logo to static/
  subtitle: future artist.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Yolanda Jin # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  dontShowLogo: true  # If you want to hide the logo, this is what you set to true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # todo: add your social accounts.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:yjin18@artic.edu'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/_imyolanda/'
      landing: true
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/yolanda-yinuo-jin-65b1642a6/'
      landing: true
    - icon: 'fab fa-youtube fa-lg'
      url: 'https://www.youtube.com/@YolandaJin'
      landing: true
  homepage: "/_work_" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  specialPages:
    - _work_
    - _dream_
    - _envolved_
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableWelcomePageBackground: false # disables the background image on the homepage
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
    main:
     - name: Work
       url: /_work_/
       weight: 1
     - name: Dream
       url: /_dream_/
       weight: 1 
     - name: Envolved
       url: /_envolved_/
       weight: 1
     - name: About
       url: /_about_/
       weight: 1
    

